# START Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
output "arn" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].arn : null
}

output "cidr_blocks" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].cidr_blocks : null
}

output "dns_entry" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].dns_entry : null
}

output "ip_address_type" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].ip_address_type : null
}

output "network_interface_ids" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].network_interface_ids : null
}

output "owner_id" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].owner_id : null
}

output "policy" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].policy : null
}

output "prefix_list_id" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].prefix_list_id : null
}

output "private_dns_enabled" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].private_dns_enabled : null
}

output "requester_managed" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].requester_managed : null
}

output "route_table_ids" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].route_table_ids : null
}

output "security_group_ids" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].security_group_ids : null
}

output "service_region" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].service_region : null
}

output "state" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].state : null
}

output "subnet_ids" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].subnet_ids : null
}

output "tags_all" {
  value = length(aws_vpc_endpoint.aws_endpoint) > 0 ? aws_vpc_endpoint.aws_endpoint[0].tags_all : null
}
# END Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
