terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 2.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.9"
}

variable "project_id" {
  type        = string
  default     = null
  description = "Project ID. If not set, creates a new project via project_generator."
}

variable "project_name" {
  type        = string
  default     = "ws-cluster-examples-test"
  description = "Project name when creating via project_generator."
}

variable "org_id" {
  type        = string
  description = "Organization ID for creating a project via project_generator."
  default     = ""
}

module "proj" {
  count        = var.project_id == null ? 1 : 0
  source       = "../project_generator"
  org_id       = var.org_id
  project_name = var.project_name
}

locals {
  project_id = var.project_id != null ? var.project_id : module.proj[0].project_id
}

# Example module calls are generated by tf_ws in modules.generated.tf
