# Generated by tf_ws - do not edit manually
import pytest
from pathlib import Path

ACTUAL_DIR = Path(__file__).parent / 'test_plan_reg_actual'
EXPECTED_DIR = Path(__file__).parent / 'test_plan_reg'

TEST_CASES = [
    ("01_module_cluster_mongodbatlas_advanced_cluster_this.yaml"),
    ("08_module_cluster_mongodbatlas_advanced_cluster_this.yaml"),
]


@pytest.mark.parametrize('filename', TEST_CASES)
def test_plan_regression(filename: str, file_regression) -> None:
    actual_file = ACTUAL_DIR / filename
    if not actual_file.exists():
        pytest.skip(f'Actual file not found: {actual_file}')
    file_regression.check(actual_file.read_text(), extension='.yaml')
