#!/usr/bin/env python
"""Generate terraform files and pytest file for workspace plan tests."""

from __future__ import annotations

from pathlib import Path

import typer
from tf_ws.models import (
    DEFAULT_TESTS_DIR,
    REPO_ROOT,
    Example,
    WsConfig,
    parse_ws_config,
    resolve_workspaces,
    sanitize_address,
)

app = typer.Typer()

VARIABLES_GENERATED_TF = "variables.generated.tf"
MODULES_GENERATED_TF = "modules.generated.tf"
TEST_PLAN_REG_DIR = "test_plan_reg"
TEST_PLAN_REG_ACTUAL_DIR = "test_plan_reg_actual"
TEST_PLAN_REG_PY = "test_plan_reg.py"
EXAMPLES_DIR_NAME = "examples"


def generate_variables_tf(config: WsConfig) -> str | None:
    exposed = config.exposed_vars()
    if not exposed:
        return None
    lines = ["# Generated by tf_ws - do not edit manually", ""]
    for var in exposed:
        lines.append(f'variable "{var.name}" {{')
        if var.module_value:
            lines.append(f"  default = {var.module_value}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def parse_include_examples(value: str, config: WsConfig) -> list[Example]:
    if value == "all":
        return config.examples
    if value == "none":
        return []
    numbers = {int(n.strip()) for n in value.split(",")}
    return [ex for ex in config.examples if ex.number in numbers]


def generate_modules_tf(
    config: WsConfig, examples: list[Example], ws_dir: Path
) -> str | None:
    if not examples:
        return None
    examples_dir = REPO_ROOT / EXAMPLES_DIR_NAME
    rel_examples = f"../../{EXAMPLES_DIR_NAME}"
    lines = ["# Generated by tf_ws - do not edit manually", ""]
    for ex in examples:
        example_path = ex.example_path(examples_dir)
        title = ex.title_from_dir(examples_dir)
        lines.append(f"# Example {ex.number:02d}: {title}")
        lines.append(f'module "ex_{ex.number:02d}" {{')
        lines.append(f'  source = "{rel_examples}/{example_path.name}"')
        for var in config.vars_for_example(ex):
            val = f"var.{var.name}" if var.expose_in_workspace else var.module_value
            lines.append(f"  {var.name} = {val}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def generate_pytest_file(config: WsConfig) -> str:
    lines = [
        "# Generated by tf_ws - do not edit manually",
        "import pytest",
        "from pathlib import Path",
        "",
        "ACTUAL_DIR = Path(__file__).parent / 'test_plan_reg_actual'",
        "EXPECTED_DIR = Path(__file__).parent / 'test_plan_reg'",
        "",
        "TEST_CASES = [",
    ]
    for ex in config.examples:
        for reg in ex.plan_regressions:
            filename = f"{ex.number:02d}_{sanitize_address(reg.address)}.yaml"
            lines.append(f'    ("{filename}"),')
    lines.extend(
        [
            "]",
            "",
            "",
            "@pytest.mark.parametrize('filename', TEST_CASES)",
            "def test_plan_regression(filename: str, file_regression) -> None:",
            "    actual_file = ACTUAL_DIR / filename",
            "    if not actual_file.exists():",
            "        pytest.skip(f'Actual file not found: {actual_file}')",
            "    file_regression.check(actual_file.read_text(), extension='.yaml')",
            "",
        ]
    )
    return "\n".join(lines)


def process_workspace(ws_dir: Path, include_examples: str = "all") -> None:
    ws_yaml = ws_dir / "ws.yaml"
    if not ws_yaml.exists():
        typer.echo(f"Skipping {ws_dir.name}: no ws.yaml found")
        return
    config = parse_ws_config(ws_yaml)
    variables_tf = ws_dir / VARIABLES_GENERATED_TF
    if content := generate_variables_tf(config):
        variables_tf.write_text(content)
        typer.echo(f"  Generated {VARIABLES_GENERATED_TF}")
    elif variables_tf.exists():
        variables_tf.unlink()
        typer.echo(f"  Removed {VARIABLES_GENERATED_TF} (no exposed vars)")
    examples = parse_include_examples(include_examples, config)
    modules_tf = ws_dir / MODULES_GENERATED_TF
    if content := generate_modules_tf(config, examples, ws_dir):
        modules_tf.write_text(content)
        typer.echo(f"  Generated {MODULES_GENERATED_TF} ({len(examples)} examples)")
    elif modules_tf.exists():
        modules_tf.unlink()
        typer.echo(f"  Removed {MODULES_GENERATED_TF} (no examples)")
    (ws_dir / TEST_PLAN_REG_DIR).mkdir(exist_ok=True)
    (ws_dir / TEST_PLAN_REG_ACTUAL_DIR).mkdir(exist_ok=True)
    pytest_file = ws_dir / TEST_PLAN_REG_PY
    pytest_file.write_text(generate_pytest_file(config))
    typer.echo(f"  Generated {TEST_PLAN_REG_PY}")


@app.command()
def main(
    ws: str = typer.Option(
        "all", "--ws", help="Workspace name or 'all' for all ws_* directories"
    ),
    tests_dir: Path = typer.Option(
        DEFAULT_TESTS_DIR, "--tests-dir", help="Path to tests directory"
    ),
    include_examples: str = typer.Option(
        "all",
        "--include-examples",
        "-e",
        help="Examples to include: all, none, or comma-separated numbers",
    ),
) -> None:
    """Generate terraform and pytest files for workspaces."""
    try:
        ws_dirs = resolve_workspaces(ws, tests_dir)
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1)
    for ws_dir in ws_dirs:
        typer.echo(f"Processing {ws_dir.name}...")
        process_workspace(ws_dir, include_examples)
    typer.echo("Done.")


if __name__ == "__main__":
    app()
