#!/usr/bin/env python
"""Generate terraform files and pytest file for workspace plan tests."""

from __future__ import annotations

from pathlib import Path

import typer
from tf_ws.models import (
    DEFAULT_TESTS_DIR,
    WsConfig,
    parse_ws_config,
    resolve_workspaces,
    sanitize_address,
)

app = typer.Typer()

VARIABLES_GENERATED_TF = "variables.generated.tf"
TEST_PLAN_REG_DIR = "test_plan_reg"
TEST_PLAN_REG_ACTUAL_DIR = "test_plan_reg_actual"
TEST_PLAN_REG_PY = "test_plan_reg.py"


def generate_variables_tf(config: WsConfig) -> str | None:
    exposed = config.exposed_vars()
    if not exposed:
        return None
    lines = ["# Generated by tf_ws - do not edit manually", ""]
    for var in exposed:
        lines.append(f'variable "{var.name}" {{')
        lines.append("  type = string")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def generate_pytest_file(config: WsConfig) -> str:
    lines = [
        "# Generated by tf_ws - do not edit manually",
        "import pytest",
        "from pathlib import Path",
        "",
        "ACTUAL_DIR = Path(__file__).parent / 'test_plan_reg_actual'",
        "EXPECTED_DIR = Path(__file__).parent / 'test_plan_reg'",
        "",
        "TEST_CASES = [",
    ]
    for ex in config.examples:
        for reg in ex.plan_regressions:
            filename = f"{ex.number:02d}_{sanitize_address(reg.address)}.yaml"
            lines.append(f'    ("{filename}"),')
    lines.append("]")
    lines.append("")
    lines.append("")
    lines.append("@pytest.mark.parametrize('filename', TEST_CASES)")
    lines.append("def test_plan_regression(filename: str, file_regression) -> None:")
    lines.append("    actual_file = ACTUAL_DIR / filename")
    lines.append("    if not actual_file.exists():")
    lines.append("        pytest.skip(f'Actual file not found: {actual_file}')")
    lines.append(
        "    file_regression.check(actual_file.read_text(), extension='.yaml')"
    )
    lines.append("")
    return "\n".join(lines)


def process_workspace(ws_dir: Path) -> None:
    ws_yaml = ws_dir / "ws.yaml"
    if not ws_yaml.exists():
        typer.echo(f"Skipping {ws_dir.name}: no ws.yaml found")
        return
    config = parse_ws_config(ws_yaml)
    variables_tf = ws_dir / VARIABLES_GENERATED_TF
    if content := generate_variables_tf(config):
        variables_tf.write_text(content)
        typer.echo(f"  Generated {VARIABLES_GENERATED_TF}")
    elif variables_tf.exists():
        variables_tf.unlink()
        typer.echo(f"  Removed {VARIABLES_GENERATED_TF} (no exposed vars)")
    (ws_dir / TEST_PLAN_REG_DIR).mkdir(exist_ok=True)
    (ws_dir / TEST_PLAN_REG_ACTUAL_DIR).mkdir(exist_ok=True)
    pytest_file = ws_dir / TEST_PLAN_REG_PY
    pytest_file.write_text(generate_pytest_file(config))
    typer.echo(f"  Generated {TEST_PLAN_REG_PY}")


@app.command()
def main(
    ws: str = typer.Option(
        "all", "--ws", help="Workspace name or 'all' for all ws_* directories"
    ),
    tests_dir: Path = typer.Option(
        DEFAULT_TESTS_DIR, "--tests-dir", help="Path to tests directory"
    ),
) -> None:
    """Generate terraform and pytest files for workspaces."""
    try:
        ws_dirs = resolve_workspaces(ws, tests_dir)
    except ValueError as e:
        typer.echo(f"Error: {e}", err=True)
        raise typer.Exit(1)
    for ws_dir in ws_dirs:
        typer.echo(f"Processing {ws_dir.name}...")
        process_workspace(ws_dir)
    typer.echo("Done.")


if __name__ == "__main__":
    app()
