name: sdlc
src_repo_url: https://github.com/terraform-mongodbatlas-modules/terraform-mongodbatlas-cluster
paths:
  # Python tooling - explicit folders (avoid .venv)
  - src_path: .github/changelog/*.py
  - src_path: .github/changelog/*.txt
    sync_mode: replace
  - src_path: .github/changelog/*.tmpl
    sync_mode: replace
  - src_path: .github/docs/
  - src_path: .github/release/
  - src_path: .github/pyproject.toml
  - src_path: .github/uv.lock
  - src_path: .github/workspace/
  - src_path: .github/dev/__init__.py
  - src_path: .github/dev/test_compat.py
  # NOTE: dev_vars.py is NOT synced - it has module-specific workspace paths
  # Workflows & actions
  - src_path: .github/workflows/
    exclude_file_patterns:
    - cleanup-test-env.yml
    - dev-integration-test.yml
    - pre-release-tests.yml
  - src_path: .github/actions/
  # GitHub config
  - src_path: .github/CODEOWNERS
  - src_path: .github/pull_request_template.md
  - src_path: .github/ISSUE_TEMPLATE/
  # Justfile with sections
  - src_path: justfile
  # Terraform docs & config
  - src_path: .terraform-docs.yml
  - src_path: .terraform-versions.yaml
  # NOTE: docs/example_readme.md is NOT synced - each module has its own template
destinations:
  - name: azure
    repo_url: https://github.com/terraform-mongodbatlas-modules/terraform-mongodbatlas-atlas-azure
    dest_path_relative: ../azure
    default_branch: main
