# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
output "authorized_date" {
  value = mongodbatlas_cloud_provider_access_authorization.this.authorized_date
}

output "feature_usages" {
  value = mongodbatlas_cloud_provider_access_authorization.this.feature_usages
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.

# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
output "created_date" {
  value = mongodbatlas_cloud_provider_access_setup.this.created_date
}

output "last_updated_date" {
  value = mongodbatlas_cloud_provider_access_setup.this.last_updated_date
}

output "role_id" {
  value = mongodbatlas_cloud_provider_access_setup.this.role_id
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
