formatter: markdown document
sections:
  hide:
  - "modules"
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
settings:
  lockfile: false
sort:
  enabled: true
  by: required
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  **NOTE**: The `data.mongodbatlas_advanced_clusters` is used by auto-scaled clusters to avoid unexpected plan changes when `instance_size` have updated.

  <!-- BEGIN_TF_INPUTS_RAW -->
  {{ .Inputs }}
  <!-- END_TF_INPUTS_RAW -->

  {{ .Outputs }}
examples_readme:
  readme_template: docs/example_readme.md
  skip_examples:
    - "13_example_import"
  code_snippet_files:
    additional: []
  template_vars:
    production_considerations_comment: |
      # if your cluster will be used in production, please read the "Production Considerations" below
    production_considerations: |
      ## Production Considerations
      - This example enables recommended production settings by default, see the [Production Recommendations (Enabled By Default)](../../README.md#production-recommendations-enabled-by-default) for details.
      - However, some recommendations must be manually set, see the [Production Recommendations (Manually Configured)](../../README.md#production-recommendations-manually-configured) list.
    skip_if_name_contains:
      - "development"
  versions_tf:
    add: |
      provider "mongodbatlas" {}
    skip_if_name_contains:
      - "development"
    generate_when_missing_only: false
    force_generate: false
    
tables:
- name: Getting Started Examples
  columns: ["cluster_type", "environment", "name"]
  link_column: name
  example_rows:
  - folder: 8
    environment: Development
    name: Development Cluster
  - folder: 1
    environment: Production
    name: Production Cluster with Auto Scaling
  - folder: 2
    environment: Production
    name: Production Cluster with Manual Scaling
- name: Examples
  readme_template: docs/example.tmpl.md
  columns: ["cluster_type", "name"]
  link_column: name
  example_rows:
  - folder: 3
    name: Cluster with Analytics Nodes
  - folder: 4
    name: Cluster with Multi Regions Local
    title_suffix: (US_EAST_1 + US_EAST_2)
  - folder: 5
    name: Cluster with Multi Regions Global
    title_suffix: (US+EU)
  - folder: 6
    name: Cluster with Multi Zones
    title_suffix: (GEOSHARDED)
  - folder: 7
    name: Cluster with Multi Clouds
    title_suffix: (AWS+AZURE)
  - folder: 9
    name: Cluster using the `replication_specs` to define Cluster Topology
  - folder: 10
    name: Cluster with Multi Zone and each zone with multiple shards
    title_suffix: (Advanced)
  - folder: 11
    name: Demonstrate how to create a module "on-top" of the module with a simplified interface
    title_suffix: (cluster_size=S/M/L)
    cluster_type: Multiple # must be explicit when there are more than one cluster_type in the example
  - folder: 12
    name: Cluster with uniform SHARDED topology using `shard_count`
