formatter: markdown document
sections:
  hide:
  - "modules"
  - "inputs"
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
sort:
  enabled: true
  by: required
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}
  
  {{ include "docs/inputs.md" }}

  {{ .Outputs }} 
