formatter: markdown document
sections:
  hide:
  - "modules"
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
settings:
  lockfile: false
sort:
  enabled: true
  by: required
content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  **NOTE**: The `data.mongodbatlas_advanced_clusters` is used by auto-scaled clusters to avoid unexpected plan changes when `instance_size` have updated.

  <!-- BEGIN_TF_INPUTS_RAW -->
  {{ .Inputs }}
  <!-- END_TF_INPUTS_RAW -->

  {{ .Outputs }}
