from __future__ import annotations

import re


def make_markers(config_filename: str, resource_type: str) -> tuple[str, str]:
    """Generate BEGIN/END marker pair for a resource type."""
    cmd = f"tf-gen --config {config_filename} --target {resource_type}"
    begin = f"# START Code generated by `{cmd}`. DO NOT EDIT."
    end = f"# END Code generated by `{cmd}`. DO NOT EDIT."
    return begin, end


def update_section(
    content: str, begin_marker: str, end_marker: str, new_content: str
) -> str:
    """Replace content between markers. Append if markers not found."""
    pattern = re.compile(
        re.escape(begin_marker) + r".*?" + re.escape(end_marker),
        re.DOTALL,
    )
    section = f"{begin_marker}\n{new_content}\n{end_marker}"

    if pattern.search(content):
        return pattern.sub(section, content)

    # Append section
    if content and not content.endswith("\n"):
        content += "\n"
    if content:
        content += "\n"
    return content + section + "\n"
