# START Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
resource "aws_vpc_endpoint" "aws_endpoint" {
  count                      = var.create_vpc_endpoint ? 1 : 0
  resource_configuration_arn = var.resource_configuration_arn
  security_group_ids         = var.security_group_ids
  service_name               = var.service_name
  service_network_arn        = var.service_network_arn
  service_region             = var.service_region
  subnet_ids                 = var.subnet_ids
  tags                       = var.tags
  vpc_endpoint_type          = var.vpc_endpoint_type
  vpc_id                     = var.vpc_id

  dynamic "subnet_configuration" {
    for_each = var.subnet_configuration == null ? [] : var.subnet_configuration
    content {
      ipv4      = subnet_configuration.value.ipv4
      ipv6      = subnet_configuration.value.ipv6
      subnet_id = subnet_configuration.value.subnet_id
    }
  }
}
# END Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
