# START Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
resource "aws_vpc_endpoint" "this" {
  auto_accept                = var.auto_accept
  ip_address_type            = var.ip_address_type
  policy                     = var.policy
  private_dns_enabled        = var.private_dns_enabled
  resource_configuration_arn = var.resource_configuration_arn
  route_table_ids            = var.route_table_ids
  security_group_ids         = var.security_group_ids
  service_name               = var.service_name
  service_network_arn        = var.service_network_arn
  service_region             = var.service_region
  subnet_ids                 = var.subnet_ids
  tags                       = var.tags
  vpc_endpoint_type          = var.vpc_endpoint_type
  vpc_id                     = var.vpc_id

  dynamic "dns_options" {
    for_each = var.dns_options == null ? [] : [var.dns_options]
    content {
      dns_record_ip_type                             = dns_options.value.dns_record_ip_type
      private_dns_only_for_inbound_resolver_endpoint = dns_options.value.private_dns_only_for_inbound_resolver_endpoint
    }
  }

  dynamic "subnet_configuration" {
    for_each = var.subnet_configuration == null ? [] : var.subnet_configuration
    content {
      ipv4      = subnet_configuration.value.ipv4
      ipv6      = subnet_configuration.value.ipv6
      subnet_id = subnet_configuration.value.subnet_id
    }
  }
}
# END Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
