# START Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
variable "vpc_id" {
  type = string
}

variable "resource_configuration_arn" {
  type     = string
  nullable = true
  default  = null
}

variable "security_group_ids" {
  type     = set(string)
  nullable = true
  default  = null
}

variable "service_name" {
  type     = string
  nullable = true
  default  = null
}

variable "service_network_arn" {
  type     = string
  nullable = true
  default  = null
}

variable "service_region" {
  type     = string
  nullable = true
  default  = null
}

variable "subnet_configuration" {
  type = set(object({
    ipv4      = optional(string),
    ipv6      = optional(string),
    subnet_id = optional(string)
  }))
  nullable = true
  default  = null
}

variable "subnet_ids" {
  type     = set(string)
  nullable = true
  default  = null
}

variable "tags" {
  type     = map(string)
  nullable = true
  default  = null
}

variable "vpc_endpoint_type" {
  type     = string
  nullable = true
  default  = null
}
# END Code generated by `tf-gen --config gen.yaml --target vpc_endpoint`. DO NOT EDIT.
