blank_issues_enabled: true
contact_links:
  - name: MongoDB Atlas Support
    url: https://support.mongodb.com/
    about: Support is provided under MongoDB Atlas support plans. Please submit support questions within the Atlas UI.
  - name: MongoDB Atlas 
    url: https://www.mongodb.com/cloud/atlas
    about: Learn more about MongoDB Atlas
