name: 'Setup Provider Dev'
description: 'Build provider from source and configure dev_overrides'
inputs:
  provider-ref:
    description: 'Provider git ref (branch, tag, or SHA)'
    required: false
    default: 'master'
runs:
  using: 'composite'
  steps:
    # Clones provider as sibling to workspace (outside cluster repo, but within allowed path)
    - name: Checkout provider
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: mongodb/terraform-provider-mongodbatlas
        ref: ${{ inputs.provider-ref }}
        path: ${{ github.workspace }}/../provider

    - name: Setup Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version-file: ${{ github.workspace }}/../provider/go.mod

    # Builds provider binary and creates dev.tfrc in cluster repo root
    # dev.tfrc points Terraform to use the local provider binary instead of registry
    - name: Build and configure provider
      shell: bash
      run: just setup-provider-dev ${{ github.workspace }}/../provider

    # Makes TF_CLI_CONFIG_FILE available to all subsequent steps in the job
    - name: Export TF_CLI_CONFIG_FILE
      shell: bash
      run: echo "TF_CLI_CONFIG_FILE=${{ github.workspace }}/dev.tfrc" >> $GITHUB_ENV
