# Generated by tf_ws - do not edit manually
from pathlib import Path

import pytest

ACTUAL_DIR = Path(__file__).parent / "plan_snapshots_actual"

TEST_CASES = [
    "01_module_cluster_mongodbatlas_advanced_cluster_this",
    "08_module_cluster_mongodbatlas_advanced_cluster_this",
]


@pytest.mark.parametrize("name", TEST_CASES)
def test_plan_snapshot(name: str, file_regression) -> None:
    actual_file = ACTUAL_DIR / f"{name}.yaml"
    assert actual_file.exists(), f'Actual file not found: {actual_file}'
    file_regression.check(actual_file.read_text(), basename=name, extension=".yaml")
