name: 'Setup Go'
description: 'Setup Go for changelog tools'
inputs:
  go-version-file:
    description: 'Path to go.mod file for version detection'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a  # v5.2.0
      with:
        go-version: ${{ inputs.go-version-file == '' && 'stable' || '' }}
        go-version-file: ${{ inputs.go-version-file }}
