# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
resource "mongodbatlas_cloud_provider_access_authorization" "this" {
  project_id = var.project_id
  role_id    = var.role_id

  dynamic "azure" {
    for_each = var.azure == null ? [] : [var.azure]
    content {
      atlas_azure_app_id   = azure.value.atlas_azure_app_id
      service_principal_id = azure.value.service_principal_id
      tenant_id            = azure.value.tenant_id
    }
  }
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
