# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
output "authorized_date" {
  value = mongodbatlas_cloud_provider_access_authorization.this.authorized_date
}

output "feature_usages" {
  value = mongodbatlas_cloud_provider_access_authorization.this.feature_usages
}

output "id" {
  value = mongodbatlas_cloud_provider_access_authorization.this.id
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
