# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
variable "project_id" {
  type = string
}

variable "role_id" {
  type = string
}

variable "azure" {
  type = object({
    atlas_azure_app_id   = string,
    service_principal_id = string,
    tenant_id            = string
  })
  nullable = true
  default  = null
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
