# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
resource "mongodbatlas_cloud_provider_access_setup" "this" {
  delete_on_create_timeout = var.delete_on_create_timeout
  project_id               = var.project_id
  provider_name            = var.provider_name

  dynamic "timeouts" {
    for_each = var.timeouts == null ? [] : [var.timeouts]
    content {
      create = timeouts.value.create
    }
  }
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
