# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
output "created_date" {
  value = mongodbatlas_cloud_provider_access_setup.this.created_date
}

output "gcp_config" {
  value = mongodbatlas_cloud_provider_access_setup.this.gcp_config
}

output "id" {
  value = mongodbatlas_cloud_provider_access_setup.this.id
}

output "last_updated_date" {
  value = mongodbatlas_cloud_provider_access_setup.this.last_updated_date
}

output "role_id" {
  value = mongodbatlas_cloud_provider_access_setup.this.role_id
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
