# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
resource "mongodbatlas_cloud_provider_access_authorization" "this" {
  project_id = var.project_id
  role_id    = var.role_id

  dynamic "aws" {
    for_each = var.aws == null ? [] : [var.aws]
    content {
      iam_assumed_role_arn = aws.value.iam_assumed_role_arn
    }
  }
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
