# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
output "authorized_date" {
  value = length(mongodbatlas_cloud_provider_access_authorization.this) > 0 ? mongodbatlas_cloud_provider_access_authorization.this[0].authorized_date : null
}

output "feature_usages" {
  value = length(mongodbatlas_cloud_provider_access_authorization.this) > 0 ? mongodbatlas_cloud_provider_access_authorization.this[0].feature_usages : null
}

output "id" {
  value = length(mongodbatlas_cloud_provider_access_authorization.this) > 0 ? mongodbatlas_cloud_provider_access_authorization.this[0].id : null
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.

# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
output "aws_config" {
  value = length(mongodbatlas_cloud_provider_access_setup.this) > 0 ? mongodbatlas_cloud_provider_access_setup.this[0].aws_config : null
}

output "created_date" {
  value = length(mongodbatlas_cloud_provider_access_setup.this) > 0 ? mongodbatlas_cloud_provider_access_setup.this[0].created_date : null
}

output "id" {
  value = length(mongodbatlas_cloud_provider_access_setup.this) > 0 ? mongodbatlas_cloud_provider_access_setup.this[0].id : null
}

output "last_updated_date" {
  value = length(mongodbatlas_cloud_provider_access_setup.this) > 0 ? mongodbatlas_cloud_provider_access_setup.this[0].last_updated_date : null
}

output "role_id" {
  value = length(mongodbatlas_cloud_provider_access_setup.this) > 0 ? mongodbatlas_cloud_provider_access_setup.this[0].role_id : null
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_setup`. DO NOT EDIT.
