# START Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
variable "project_id" {
  type = string
}

variable "role_id" {
  type = string
}

variable "aws" {
  type = object({
    iam_assumed_role_arn = string
  })
  nullable = true
  default  = null
}
# END Code generated by `tf-gen --config gen.yaml --target cloud_provider_access_authorization`. DO NOT EDIT.
