name: Validate Region Mappings
# === DO_NOT_EDIT: path-sync header ===
on:
  schedule:
    - cron: '0 8 * * 1'  # Weekly on Monday at 8:00 AM UTC
  workflow_dispatch:

env:
  MONGODB_ATLAS_PROJECT_ID: ${{ vars.MONGODB_ATLAS_PROJECT_ID_SNAPSHOT_TEST }}
  MONGODB_ATLAS_CLIENT_ID: ${{ secrets.MONGODB_ATLAS_CLIENT_ID }}
  MONGODB_ATLAS_CLIENT_SECRET: ${{ secrets.MONGODB_ATLAS_CLIENT_SECRET }}
  # MONGODB_ATLAS_BASE_URL: ${{ secrets.MONGODB_ATLAS_BASE_URL }} Currently only `MONGODB_ATLAS_OPS_MANAGER_URL` is read from env-vars CLOUDP-383021
  MONGODB_ATLAS_OPS_MANAGER_URL: ${{ secrets.MONGODB_ATLAS_BASE_URL }}
# === OK_EDIT: path-sync header ===
# Add module specific env-vars here

jobs:
  # === DO_NOT_EDIT: path-sync job-validate ===
  validate-regions:
    name: Validate Region Mappings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ./.github/actions/setup
        with:
          just: 'true'
          uv: 'true'
          terraform: 'true'

      - name: Setup AtlasCLI
        uses: mongodb/atlas-github-action@07d212bf80c068dfcfbf6e15b22c61ae6e66d96e # v0.2.0

  # === OK_EDIT: path-sync job-validate ===
  # ADD cloud provider login and validate regions step

  # === DO_NOT_EDIT: path-sync job-slack ===
  slack-notification:
    needs: [validate-regions]
    if: ${{ github.event_name == 'schedule' && !cancelled() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "${{ github.event.repository.name }}: Validate Region Mappings scheduled run failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: *${{ github.event.repository.name }}: Validate Region Mappings scheduled run failed* ${{ secrets.SLACK_ONCALL_TAG }} <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View failed run>"
                  }
                }
              ]
            }
  # === OK_EDIT: path-sync job-slack ===
